### PR TITLE
Add kubectl during CI to pass validation 

### PR DESCRIPTION
**Pull request by arshchimni**
## Description
Add kubectl binary to ci step in makefile

## Checklist:

I have:

- [x] checked my changes follow the style of the existing code / OpenFaaS repos
- [x] updated the documentation and/or roadmap in README.md
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide

### CODE REVIEW

**Comment by utsavanand2** [comment]
Hey @arshchimni !
It would be really great if you can squash your two commits into one and signoff your commit with:
$ git reset HEAD~2
$ git add .
$ git commit -s

Thanks!

**Comment by arshchimni** [comment]
Sure no problem

**Comment by alexellis** [comment]
Unfortunately you have now ended up with 4 commits.. @utsavanand2 please could you assist?

**Comment by utsavanand2** [comment]
@arshchimni The code for installation of kubectl should really lie inside of hack/install-ci.sh. You have made changes to ci.sh (which mainly deals with the CI process itself) and not the creating of the testing environment.

**Comment by arshchimni** [comment]
I'll close this pr and reopen a new one

**Pull request closed without merging**
