### PR TITLE
Fix Kubectl not present during ci

### PR DESCRIPTION
**Pull request by arshchimni**
## Description

update dpkg

I have:

- [x] checked my changes follow the style of the existing code / OpenFaaS repos
- [x] updated the documentation and/or roadmap in README.md
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by alexellis** [comment]
This can be closed due to https://github.com/openfaas-incubator/ofc-bootstrap/pull/128

@arshchimni thank you so much for having a go at this.

**Comment by arshchimni** [comment]
Sure. Thanks @alexellis

**Comment by alexellis** [comment]
We have other items that you could help with too :)

**Pull request closed without merging**
