### PR TITLE
Missing step in Run Ofc-bootstrap

### PR DESCRIPTION
**Pull request by Buraburaite**
For non-Go coders, having the build step be explicit saves some time and frustration.

## Checklist:

I have:

- [ ] checked my changes follow the style of the existing code / OpenFaaS repos
- [x] updated the documentation and/or roadmap in README.md
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi there. Thank you for your feedback. Users are supposed to use the binary releases and are not expected to compile the Go code. 

I will check the instructions to see if this can be made more explicit. 

Alex

**Comment by Buraburaite** [comment]
Well, I did download the binary to usr/local/bin and run chmod +x on it. But when I run it in I get ./ofc-bootstrap is not a file or directory. I run it from the cloned github repo. Not sure if I'm missing a step or something. I got it work after building. I'm on Ubuntu 18.04.

**Comment by alexellis** [comment]
Please can you share the exact link that you used?

**Comment by Buraburaite** [comment]
Instructions I followed: https://github.com/openfaas-incubator/ofc-bootstrap

Binary I downloaded: https://github.com/openfaas-incubator/ofc-bootstrap/releases/download/0.6.4/ofc-bootstrap

**Comment by alexellis** [comment]
The option with no suffix is for Linux. The option of a suffix of Darwin is for MacOS.

What computer you running the binary on?

`uname -a ; cat /etc/os-release`

**Comment by Buraburaite** [comment]
Screenshot from 2019-08-05 14-14-20

**Comment by Buraburaite** [comment]
I have to go to work, but I hope this was at least on the whole helpful. Chances are it's my fault somehow, my education on file-system stuff is incomplete. I'll check back tomorrow in case you have any more questions I can help with. Thanks Alex, have a good day.

**Comment by alexellis** [comment]
I checked the binary on my own Linux Ubuntu x86 machine and it worked fine. Please can you download fresh and inspect the result before going ahead and running it?

**Comment by Buraburaite** [comment]
Deleted the local build of ofc-bootstrap and the one in usr/local/bin, redownloaded from the same link, moved and chmod, then tried to run from the cloned repo directory and terminal didn't find it. I checked my .profile and .bash_rc, but I don't see a problem. I'll even upload them if you want, but here are my Go-related variables:

`export PATH=$PATH:/usr/local/go/bin`
`export GOPATH=$HOME/go`

Really not sure what's different about my set up, but I can get it going by building it locally.

Screenshot from 2019-08-08 13-19-46

**Comment by alexellis** [comment]
Run it without the prefix of ./

**Comment by Buraburaite** [comment]
Tried that plus a couple variations
Screenshot from 2019-08-08 15-41-24

**Comment by alexellis** [comment]
You have to remove the prefix that you're adding.

Try: `/usr/local/bin/ofc-bootstrap`

**Comment by Buraburaite** [comment]
Okay, `/usr/local/bin/ofc-bootstrap` works. And now `ofc-bootstrap` works as well, whereas before it gave "command not found". It literally was not working before, with or without the prefix, as can be seen in the image I sent. I'm not going to question it though. Thanks Alex!

**Comment by alexellis** [comment]
Sorry about the confusion. I think it's the prefix of `./` that caused a problem. I'll have another look at the readme soon to check it again.

**Comment by Buraburaite** [comment]
It's alright, something is probably weird with my machine, wouldn't be the first time. I was hoping to slightly improve the README but I guess it didn't turn out that way :/ Wish everyone the best though!

**Pull request closed without merging**
