### PR TITLE
Rename system-metrics to metrics for 0.12.0 of OFC

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

## Description

Rename system-metrics to metrics for 0.12.0 of OFC

* Relates to issue https://github.com/openfaas/openfaas-cloud/issues/573

cc @Waterdrips

### CODE REVIEW

**Comment by alexellis** [comment]
Could you test before we merge?

**Comment by alexellis** [comment]
With GitLab, TLS and K8s 1.16 in k3d I'm seeing:

```
 Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: webhook.cert-manager.io/v1beta1: the server is currently unable to handle the request
```

**Comment by Waterdrips** [comment]
> With GitLab, TLS and K8s 1.16 in k3d I'm seeing:
> 
> ```
>  Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: webhook.cert-manager.io/v1beta1: the server is currently unable to handle the request
> ```

GitHub, K3s (Civo Kubernetes) (v1.16 k8s)
Iv got it working, (https://system.heyal.uk)

Ill try a GitLab install now

**Comment by alexellis** [comment]
It could be a timing issue. We might need to halt if OpenFaaS didn't come up as expected.

**Pull request merged**
