### PR TITLE
Bump go-execute and use args for secrets

### PR DESCRIPTION
**Pull request by alexellis**
## Description

    * Using args for secrets instead of the command value means that
    secrets can now contain spaces
    * The latest go-execute version makes streaming to STDIO optional
    so that values can be hidden or automated in parallel without
    creating spam on the console

## How Has This Been Tested?    

    Tested that ofc-bootstrap completed with k3d, but didn't try with
    a real domain / TLS and OAuth.
    
    Fixes: #16

### CODE REVIEW

**Comment by alexellis** [comment]
@Waterdrips please could you review & test in your setup?

**Comment by Waterdrips** [comment]
Looks like the tests failed

**Comment by alexellis** [comment]
I tried running locally which was ok, can you see what didn't go right?

**Comment by Waterdrips** [comment]
ok, go 1.11 fails to build, go 1.13 works.

It appears to be the Error Wrapping (https://go.googlesource.com/proposal/+/master/design/29934-error-values.md) released in go 1.13.

can we bump the dockerfile version for the Dockerfile.redist ? (Works locally)

**Comment by alexellis** [comment]
Thanks, I've made that change now.

**Pull request merged**
