### PR TITLE
Fix download url

### PR DESCRIPTION
**Pull request by brandonkal**
## Description
Update and fix download url

## How Has This Been Tested?
The url responds

## Checklist:

I have:

- [x] checked my changes follow the style of the existing code / OpenFaaS repos
- [ ] updated the documentation and/or roadmap in README.md
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Please see the message from Derek. 

I assume this is not a fix given that it works? More of an update?

**Comment by brandonkal** [comment]
True. More of an update. Because of Derek's sign off requirement, it looks like it is not possible to make contributions from the GitHub web UI. Feel free to push the change manually as cloning this down is not an option on my end at the moment. Sorry.

**Comment by alexellis** [comment]
There's no need to use the `git` command-line, I'm not sure if you read the contributing guide yet?

```
Add alexellis to the .DEREK.yml file

We need to add alexellis to the .DEREK.yml file for project maintainer
duties.

Signed-off-by: Alex Ellis <alex@openfaas.com>
```

Here is an example of a commit message that you can customise and enter into the GitHub UI, which will add the signed-off-by message. Feel free to use it.

I'm curious about why you couldn't clone a GitHub repository to a temporary directory on your computer or to a VM somewhere and add a commit?

**Comment by brandonkal** [comment]
Yes, I've seen that. As far as I am aware the GitHub UI provides no way to amend a commit message.
To your question it is simply a matter of available time and being mobile. I can make it happen later but it is a low priority change and next time I'll just open an issue for small things.

**Comment by alexellis** [comment]
If you don't have time to do the PR properly, then your suggestion would be great, an issue. That's how we handle typos anyway. 

Thanks for your interest and feel free to join us on Slack if you haven't already.

**Pull request closed without merging**
